apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - ""
          resources:
            - pods/exec
          verbs:
            - create

configMapGenerator:
  - name: argocd-cm
    literals:
      - exec.enabled=true
    behavior: merge
