apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
spec:
  selector:
    matchLabels:
      app: nginx-sample
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
