---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-test
  namespace: acme-staging
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    test: AgAUWJ6vwn6yMv6Njn47bvVy0Y6CRF3j0jhjA5ug62qodlrcfRe721V8B5W2HWTX28CdvZTcT6Qe/VucgUxEOhMEv/lxHoGhzD7O9fs6VxAjf/lXom0ZuxG72CK9jzsxovDsOCc7g+Y2WEF+ygh1EXH097ksDZy4FXhqjVTvhP0ppAWWpPHadOtJx5yhXH9c96npiwd6jCYKdzELWKJGHBH+t1cvOQiUpJz+Lb7ep0F8RTJgC5d+NjxfJj7xMgIKTpUVZaEJWBzFKa8rAb/k7q4VGYGcMcjhYvcRaOCzq3avCTplWE9HTHBaT+CBNYzAn8zn5HXUze+51lfhDhAtvw9Jtm++Zfr2fCyrcAymAyUT5vJ/VvymGunVMX3dOG3abCX8KwDan3UNjFg6Sl+EdJeDnsre4w4Ofg4azGVNblpwxWceiy7H5svtDKVmfpjqQ21Snk/xuS3F8pSiX6xlTacGeAn/6jJfHpBGiikkauAvwsFCr1by88Ilody2/10DSLAIDjYI+kcOfpwtxMB9PS4RcW8JwzbgqBvAe9tWJNwYezFQO5UH3cM5CA6/IYnzU7zSaB+zhJGnI5dyDbnvgK8UAHy5izKD04XcFxC1nByxps5XLMTzvG+oKFazbmy4H9AcUY+c5LLsEmGYMMaSwvHirs1G+O6//nSplH+AnnEh+MS4hHgOahjSWRRsPSOMii//MTMHFKxazMJOAw==
  template:
    metadata:
      creationTimestamp: null
      name: secret-test
      namespace: acme-staging
