---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-test
  namespace: acme-staging
spec:
  encryptedData:
    test: AgBScRklqCKkRPZuWS4IrsAJ/Bsf/0Eh8CNkdUSIp8y2KhheagfqsCaxHtkA4TSett0peXc0JwD7QgwvCN6cvrzqkwoAO/I54ndGWlUHWC6yuLotyfZ0GpLUhY8hdCxkiNxQ/INXgNFkXeDxEcMa9QYDbi5SQgHbGKtbzWDd80yzuzSPl09cZMoA0EZrJ92MxWtF9TMiOy0nRhi0CwQW9HWt0WMPmMQBue8meCayoUwLBa6QIUlMcu9pBk8Fh3SM1WouNWobBb65YdQsI0qythS8SDWfR4StrevKrwojpq0O2tLs7yoMuuiZMe3aTmjmUvKClJay0k7ZNq6KR2fS1CV3X0/p2+WxoWEm3BInFy77vrQTiXDtt885TY81j7s/JVUKLCfw/g2vkMuh3iXvcVhLotrMbqTl71GrNoA7c9PsF24GxsRK4vu06aV0NMhZAPtBxyAkJmzbxa35Xe0XsM4uxxhU5XCRVmIVhoz+NX7YSvVqs7YfDEf7+Gb+MKhFtmsTHi33gVJEJqCAbMehFBV6fWQqqOvYxAJEjAehl9K+lsMLxGZbz12i9MiGhw1oCszfOsyts/KClX/fwQqwQbcXC39pkGWJCMsvkgZjnNdn295sHxwORGaCZGb7CUX96ua8TdhD7PU4gSZIst0koLZHc57nWuYWhOTZbLb2+UYD85/ckRBpKdxQqYikEv/WzduoCnFMgQ==
  template:
    metadata:
      creationTimestamp: null
      name: secret-test
      namespace: acme-staging
