apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: acme-staging
  namespace: argocd
spec:
  description: Acme Staging Project
  destinations:
    - namespace: acme-staging
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/ruslanguns/application-sets.git
