apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: acme-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
